-- Bulk Test Data SQL Script for Content Freshness Alert Plugin (PRODUCTIVITY & TIME MANAGEMENT)
-- This script generates test posts focused on productivity and time management topics
-- Run this in phpMyAdmin or MySQL command line

-- Set the database (replace 'check_address' with your database name)
USE check_address;

-- First, remove existing test posts
DELETE FROM wp_posts WHERE post_title LIKE '%Recent Blog Post%' OR post_title LIKE '%Monthly Newsletter%' OR post_title LIKE '%Quarterly Report%' OR post_title LIKE '%Old Tutorial%' OR post_title LIKE '%Ancient Article%' OR post_title LIKE '%Test Page%';

-- Create test posts with different age ranges - Productivity & Time Management Focus
-- Very Fresh Posts (0-30 days)
INSERT INTO wp_posts (post_title, post_content, post_excerpt, post_status, post_type, post_date, post_date_gmt, post_modified, post_modified_gmt, post_author, comment_status, ping_status, post_name, post_parent, menu_order, post_mime_type, comment_count, to_ping, pinged, post_content_filtered) VALUES
('The Pomodoro Technique: Boost Your Focus in 25-Minute Sprints', 'Learn how the Pomodoro Technique can dramatically improve your productivity by breaking work into focused 25-minute intervals followed by short breaks. This time management method helps maintain concentration and prevents burnout.', '', 'publish', 'post', DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY), 1, 'open', 'open', 'pomodoro-technique-focus-sprints', 0, 0, '', 0, '', '', ''),
('Time Blocking: The Secret to Taking Control of Your Schedule', 'Discover how time blocking can transform your daily routine by allocating specific time slots for different activities. This powerful productivity method helps you prioritize tasks and eliminate distractions.', '', 'publish', 'post', DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY), 1, 'open', 'open', 'time-blocking-schedule-control', 0, 0, '', 0, '', '', ''),
('Eisenhower Matrix: Prioritize Tasks Like a Pro', 'Master the art of task prioritization using the Eisenhower Matrix. Learn to categorize tasks by urgency and importance, helping you focus on what truly matters and eliminate time-wasting activities.', '', 'publish', 'post', DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY), 1, 'open', 'open', 'eisenhower-matrix-prioritize-tasks', 0, 0, '', 0, '', '', ''),
('Digital Minimalism: Reclaim Your Focus in a Distracted World', 'Explore how digital minimalism can help you regain control over your attention and time. Learn practical strategies to reduce digital distractions and create a more intentional relationship with technology.', '', 'publish', 'post', DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY), 1, 'open', 'open', 'digital-minimalism-reclaim-focus', 0, 0, '', 0, '', '', ''),
('The Two-Minute Rule: Stop Procrastinating on Small Tasks', 'Implement the two-minute rule to overcome procrastination and build momentum. If a task takes less than two minutes, do it immediately. This simple principle can dramatically improve your productivity.', '', 'publish', 'post', DATE_SUB(NOW(), INTERVAL 7 DAY), DATE_SUB(NOW(), INTERVAL 7 DAY), DATE_SUB(NOW(), INTERVAL 7 DAY), DATE_SUB(NOW(), INTERVAL 7 DAY), 1, 'open', 'open', 'two-minute-rule-stop-procrastination', 0, 0, '', 0, '', '', ''),
('Deep Work: How to Achieve Flow State and Peak Performance', 'Learn the principles of deep work and how to create an environment that supports sustained focus. Discover techniques for entering flow state and maximizing your cognitive performance.', '', 'publish', 'post', DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_SUB(NOW(), INTERVAL 10 DAY), 1, 'open', 'open', 'deep-work-flow-state-performance', 0, 0, '', 0, '', '', ''),
('Getting Things Done (GTD): The Ultimate Productivity System', 'Master David Allen''s Getting Things Done methodology to organize your life and reduce stress. Learn how to capture, clarify, organize, reflect, and engage with your tasks effectively.', '', 'publish', 'post', DATE_SUB(NOW(), INTERVAL 15 DAY), DATE_SUB(NOW(), INTERVAL 15 DAY), DATE_SUB(NOW(), INTERVAL 15 DAY), DATE_SUB(NOW(), INTERVAL 15 DAY), 1, 'open', 'open', 'getting-things-done-gtd-system', 0, 0, '', 0, '', '', ''),
('Morning Routines of Highly Productive People', 'Discover the morning routines that set successful people up for productive days. Learn how to design a morning routine that energizes you and creates momentum for the rest of your day.', '', 'publish', 'post', DATE_SUB(NOW(), INTERVAL 20 DAY), DATE_SUB(NOW(), INTERVAL 20 DAY), DATE_SUB(NOW(), INTERVAL 20 DAY), DATE_SUB(NOW(), INTERVAL 20 DAY), 1, 'open', 'open', 'morning-routines-productive-people', 0, 0, '', 0, '', '', ''),
('The Power of Saying No: Protect Your Time and Energy', 'Learn how to say no effectively to protect your time and energy. Discover strategies for setting boundaries and prioritizing your own goals over others'' requests.', '', 'publish', 'post', DATE_SUB(NOW(), INTERVAL 25 DAY), DATE_SUB(NOW(), INTERVAL 25 DAY), DATE_SUB(NOW(), INTERVAL 25 DAY), DATE_SUB(NOW(), INTERVAL 25 DAY), 1, 'open', 'open', 'power-saying-no-protect-time', 0, 0, '', 0, '', '', ''),
('Batch Processing: Work Smarter, Not Harder', 'Master the art of batch processing to increase efficiency and reduce context switching. Learn how to group similar tasks together and complete them in focused sessions.', '', 'publish', 'post', DATE_SUB(NOW(), INTERVAL 30 DAY), DATE_SUB(NOW(), INTERVAL 30 DAY), DATE_SUB(NOW(), INTERVAL 30 DAY), DATE_SUB(NOW(), INTERVAL 30 DAY), 1, 'open', 'open', 'batch-processing-work-smarter', 0, 0, '', 0, '', '', '');

-- Fresh Posts (31-180 days)
INSERT INTO wp_posts (post_title, post_content, post_excerpt, post_status, post_type, post_date, post_date_gmt, post_modified, post_modified_gmt, post_author, comment_status, ping_status, post_name, post_parent, menu_order, post_mime_type, comment_count, to_ping, pinged, post_content_filtered) VALUES
('Habit Stacking: Build Better Routines One Step at a Time', 'Learn how habit stacking can help you build consistent routines by attaching new habits to existing ones. This powerful technique makes behavior change more sustainable and automatic.', '', 'publish', 'post', DATE_SUB(NOW(), INTERVAL 31 DAY), DATE_SUB(NOW(), INTERVAL 31 DAY), DATE_SUB(NOW(), INTERVAL 31 DAY), DATE_SUB(NOW(), INTERVAL 31 DAY), 1, 'open', 'open', 'habit-stacking-build-routines', 0, 0, '', 0, '', '', ''),
('The 80/20 Rule: Focus on What Really Matters', 'Discover how the Pareto Principle can revolutionize your productivity by helping you identify the 20% of activities that generate 80% of your results. Learn to eliminate time-wasting tasks and focus on high-impact work.', '', 'publish', 'post', DATE_SUB(NOW(), INTERVAL 45 DAY), DATE_SUB(NOW(), INTERVAL 45 DAY), DATE_SUB(NOW(), INTERVAL 45 DAY), DATE_SUB(NOW(), INTERVAL 45 DAY), 1, 'open', 'open', '80-20-rule-focus-matters', 0, 0, '', 0, '', '', ''),
('Energy Management: Work With Your Natural Rhythms', 'Understand how to align your work with your natural energy cycles for maximum productivity. Learn to identify your peak performance times and schedule demanding tasks accordingly.', '', 'publish', 'post', DATE_SUB(NOW(), INTERVAL 60 DAY), DATE_SUB(NOW(), INTERVAL 60 DAY), DATE_SUB(NOW(), INTERVAL 60 DAY), DATE_SUB(NOW(), INTERVAL 60 DAY), 1, 'open', 'open', 'energy-management-natural-rhythms', 0, 0, '', 0, '', '', ''),
('Single-Tasking: The Lost Art of Focused Attention', 'Rediscover the power of single-tasking in our multitasking world. Learn why focusing on one task at a time leads to better results, reduced stress, and improved quality of work.', '', 'publish', 'post', DATE_SUB(NOW(), INTERVAL 90 DAY), DATE_SUB(NOW(), INTERVAL 90 DAY), DATE_SUB(NOW(), INTERVAL 90 DAY), DATE_SUB(NOW(), INTERVAL 90 DAY), 1, 'open', 'open', 'single-tasking-focused-attention', 0, 0, '', 0, '', '', ''),
('The Power of Deadlines: How Constraints Boost Creativity', 'Explore how deadlines and time constraints can actually enhance your creativity and productivity. Learn to use artificial deadlines strategically to overcome procrastination and generate better results.', '', 'publish', 'post', DATE_SUB(NOW(), INTERVAL 120 DAY), DATE_SUB(NOW(), INTERVAL 120 DAY), DATE_SUB(NOW(), INTERVAL 120 DAY), DATE_SUB(NOW(), INTERVAL 120 DAY), 1, 'open', 'open', 'power-deadlines-constraints-creativity', 0, 0, '', 0, '', '', ''),
('Work-Life Balance: Setting Boundaries in a Connected World', 'Master the art of work-life balance by setting clear boundaries between your professional and personal time. Learn practical strategies to protect your personal time and prevent burnout.', '', 'publish', 'post', DATE_SUB(NOW(), INTERVAL 150 DAY), DATE_SUB(NOW(), INTERVAL 150 DAY), DATE_SUB(NOW(), INTERVAL 150 DAY), DATE_SUB(NOW(), INTERVAL 150 DAY), 1, 'open', 'open', 'work-life-balance-boundaries', 0, 0, '', 0, '', '', ''),
('The Compound Effect: Small Changes, Big Results', 'Understand how small, consistent actions compound over time to create extraordinary results. Learn to build momentum through daily habits and incremental improvements.', '', 'publish', 'post', DATE_SUB(NOW(), INTERVAL 180 DAY), DATE_SUB(NOW(), INTERVAL 180 DAY), DATE_SUB(NOW(), INTERVAL 180 DAY), DATE_SUB(NOW(), INTERVAL 180 DAY), 1, 'open', 'open', 'compound-effect-small-changes', 0, 0, '', 0, '', '', '');

-- Aging Posts (181-365 days)
INSERT INTO wp_posts (post_title, post_content, post_excerpt, post_status, post_type, post_date, post_date_gmt, post_modified, post_modified_gmt, post_author, comment_status, ping_status, post_name, post_parent, menu_order, post_mime_type, comment_count, to_ping, pinged, post_content_filtered) VALUES
('The Psychology of Procrastination: Understanding Why We Delay', 'Dive deep into the psychological roots of procrastination and learn evidence-based strategies to overcome this common productivity killer. Understand the emotional and cognitive factors that drive delay behavior.', '', 'publish', 'post', DATE_SUB(NOW(), INTERVAL 181 DAY), DATE_SUB(NOW(), INTERVAL 181 DAY), DATE_SUB(NOW(), INTERVAL 181 DAY), DATE_SUB(NOW(), INTERVAL 181 DAY), 1, 'open', 'open', 'psychology-procrastination-understand-delay', 0, 0, '', 0, '', '', ''),
('Mind Mapping: Visual Thinking for Better Organization', 'Master the art of mind mapping to organize your thoughts, plan projects, and boost creativity. Learn how visual thinking can help you process information more effectively and generate innovative solutions.', '', 'publish', 'post', DATE_SUB(NOW(), INTERVAL 200 DAY), DATE_SUB(NOW(), INTERVAL 200 DAY), DATE_SUB(NOW(), INTERVAL 200 DAY), DATE_SUB(NOW(), INTERVAL 200 DAY), 1, 'open', 'open', 'mind-mapping-visual-thinking-organization', 0, 0, '', 0, '', '', ''),
('The Science of Motivation: What Really Drives Us', 'Explore the latest research on motivation and learn how to harness both intrinsic and extrinsic motivation to achieve your goals. Understand the difference between motivation and discipline.', '', 'publish', 'post', DATE_SUB(NOW(), INTERVAL 250 DAY), DATE_SUB(NOW(), INTERVAL 250 DAY), DATE_SUB(NOW(), INTERVAL 250 DAY), DATE_SUB(NOW(), INTERVAL 250 DAY), 1, 'open', 'open', 'science-motivation-what-drives-us', 0, 0, '', 0, '', '', ''),
('Decision Fatigue: How to Make Better Choices Throughout the Day', 'Learn about decision fatigue and how it impacts your productivity. Discover strategies to reduce the number of decisions you need to make and preserve mental energy for important choices.', '', 'publish', 'post', DATE_SUB(NOW(), INTERVAL 300 DAY), DATE_SUB(NOW(), INTERVAL 300 DAY), DATE_SUB(NOW(), INTERVAL 300 DAY), DATE_SUB(NOW(), INTERVAL 300 DAY), 1, 'open', 'open', 'decision-fatigue-better-choices', 0, 0, '', 0, '', '', ''),
('The Art of Delegation: Multiplying Your Productivity', 'Master the skill of effective delegation to multiply your productivity and develop your team. Learn how to identify tasks to delegate and communicate expectations clearly.', '', 'publish', 'post', DATE_SUB(NOW(), INTERVAL 365 DAY), DATE_SUB(NOW(), INTERVAL 365 DAY), DATE_SUB(NOW(), INTERVAL 365 DAY), DATE_SUB(NOW(), INTERVAL 365 DAY), 1, 'open', 'open', 'art-delegation-multiply-productivity', 0, 0, '', 0, '', '', '');

-- Stale Posts (366-730 days)
INSERT INTO wp_posts (post_title, post_content, post_excerpt, post_status, post_type, post_date, post_date_gmt, post_modified, post_modified_gmt, post_author, comment_status, ping_status, post_name, post_parent, menu_order, post_mime_type, comment_count, to_ping, pinged, post_content_filtered) VALUES
('The Myth of Multitasking: Why It''s Killing Your Productivity', 'Debunk the myth of multitasking and learn why focusing on one task at a time is far more effective. Understand the cognitive costs of task-switching and how to minimize distractions.', '', 'publish', 'post', DATE_SUB(NOW(), INTERVAL 366 DAY), DATE_SUB(NOW(), INTERVAL 366 DAY), DATE_SUB(NOW(), INTERVAL 366 DAY), DATE_SUB(NOW(), INTERVAL 366 DAY), 1, 'open', 'open', 'myth-multitasking-killing-productivity', 0, 0, '', 0, '', '', ''),
('Building a Second Brain: Organize Your Digital Life', 'Learn how to build a personal knowledge management system that helps you capture, organize, and retrieve information effectively. Discover tools and techniques for digital organization.', '', 'publish', 'post', DATE_SUB(NOW(), INTERVAL 400 DAY), DATE_SUB(NOW(), INTERVAL 400 DAY), DATE_SUB(NOW(), INTERVAL 400 DAY), DATE_SUB(NOW(), INTERVAL 400 DAY), 1, 'open', 'open', 'building-second-brain-organize-digital', 0, 0, '', 0, '', '', ''),
('The Power of Systems: Automate Your Way to Success', 'Discover how to create systems and processes that work for you even when you''re not actively thinking about them. Learn to automate routine tasks and focus on high-value activities.', '', 'publish', 'post', DATE_SUB(NOW(), INTERVAL 500 DAY), DATE_SUB(NOW(), INTERVAL 500 DAY), DATE_SUB(NOW(), INTERVAL 500 DAY), DATE_SUB(NOW(), INTERVAL 500 DAY), 1, 'open', 'open', 'power-systems-automate-success', 0, 0, '', 0, '', '', ''),
('Stress Management: Keeping Calm Under Pressure', 'Learn effective stress management techniques to maintain productivity and well-being during challenging times. Discover how to build resilience and prevent burnout.', '', 'publish', 'post', DATE_SUB(NOW(), INTERVAL 600 DAY), DATE_SUB(NOW(), INTERVAL 600 DAY), DATE_SUB(NOW(), INTERVAL 600 DAY), DATE_SUB(NOW(), INTERVAL 600 DAY), 1, 'open', 'open', 'stress-management-calm-pressure', 0, 0, '', 0, '', '', ''),
('The Future of Work: Adapting to Remote Productivity', 'Explore how the future of work is changing and learn strategies to thrive in remote and hybrid work environments. Understand the unique challenges and opportunities of distributed teams.', '', 'publish', 'post', DATE_SUB(NOW(), INTERVAL 730 DAY), DATE_SUB(NOW(), INTERVAL 730 DAY), DATE_SUB(NOW(), INTERVAL 730 DAY), DATE_SUB(NOW(), INTERVAL 730 DAY), 1, 'open', 'open', 'future-work-remote-productivity', 0, 0, '', 0, '', '', '');

-- Very Stale Posts (731+ days)
INSERT INTO wp_posts (post_title, post_content, post_excerpt, post_status, post_type, post_date, post_date_gmt, post_modified, post_modified_gmt, post_author, comment_status, ping_status, post_name, post_parent, menu_order, post_mime_type, comment_count, to_ping, pinged, post_content_filtered) VALUES
('The Productivity Revolution: How Technology Changed Everything', 'Explore how the digital revolution transformed productivity and time management. Learn about the evolution of productivity tools and how they''ve shaped modern work practices.', '', 'publish', 'post', DATE_SUB(NOW(), INTERVAL 731 DAY), DATE_SUB(NOW(), INTERVAL 731 DAY), DATE_SUB(NOW(), INTERVAL 731 DAY), DATE_SUB(NOW(), INTERVAL 731 DAY), 1, 'open', 'open', 'productivity-revolution-technology-changed', 0, 0, '', 0, '', '', ''),
('Mastering the Art of Focus in a Distracted World', 'Learn timeless principles of focus and concentration that remain relevant despite technological changes. Discover how to cultivate deep attention in an age of constant interruptions.', '', 'publish', 'post', DATE_SUB(NOW(), INTERVAL 800 DAY), DATE_SUB(NOW(), INTERVAL 800 DAY), DATE_SUB(NOW(), INTERVAL 800 DAY), DATE_SUB(NOW(), INTERVAL 800 DAY), 1, 'open', 'open', 'mastering-art-focus-distracted-world', 0, 0, '', 0, '', '', ''),
('The Psychology of Peak Performance: What Science Tells Us', 'Dive into the scientific research on peak performance and learn evidence-based strategies for optimizing your cognitive abilities and achieving consistent high performance.', '', 'publish', 'post', DATE_SUB(NOW(), INTERVAL 1000 DAY), DATE_SUB(NOW(), INTERVAL 1000 DAY), DATE_SUB(NOW(), INTERVAL 1000 DAY), DATE_SUB(NOW(), INTERVAL 1000 DAY), 1, 'open', 'open', 'psychology-peak-performance-science', 0, 0, '', 0, '', '', ''),
('Building Sustainable Productivity Habits That Last', 'Learn how to build productivity habits that stand the test of time. Discover the difference between quick fixes and sustainable systems that create lasting change.', '', 'publish', 'post', DATE_SUB(NOW(), INTERVAL 1200 DAY), DATE_SUB(NOW(), INTERVAL 1200 DAY), DATE_SUB(NOW(), INTERVAL 1200 DAY), DATE_SUB(NOW(), INTERVAL 1200 DAY), 1, 'open', 'open', 'building-sustainable-productivity-habits', 0, 0, '', 0, '', '', ''),
('The Fundamentals of Time Management: Core Principles', 'Master the fundamental principles of time management that form the foundation of all productivity systems. Learn timeless strategies that work regardless of your tools or technology.', '', 'publish', 'post', DATE_SUB(NOW(), INTERVAL 1500 DAY), DATE_SUB(NOW(), INTERVAL 1500 DAY), DATE_SUB(NOW(), INTERVAL 1500 DAY), DATE_SUB(NOW(), INTERVAL 1500 DAY), 1, 'open', 'open', 'fundamentals-time-management-principles', 0, 0, '', 0, '', '', '');

-- Create test pages with productivity-focused content
INSERT INTO wp_posts (post_title, post_content, post_excerpt, post_status, post_type, post_date, post_date_gmt, post_modified, post_modified_gmt, post_author, comment_status, ping_status, post_name, post_parent, menu_order, post_mime_type, comment_count, to_ping, pinged, post_content_filtered) VALUES
('Productivity Resources: Tools and Techniques Guide', 'A comprehensive guide to productivity tools, techniques, and methodologies. Discover the best resources for improving your time management and achieving your goals.', '', 'publish', 'page', DATE_SUB(NOW(), INTERVAL 100 DAY), DATE_SUB(NOW(), INTERVAL 100 DAY), DATE_SUB(NOW(), INTERVAL 100 DAY), DATE_SUB(NOW(), INTERVAL 100 DAY), 1, 'closed', 'closed', 'productivity-resources-tools-guide', 0, 0, '', 0, '', '', ''),
('Time Management Fundamentals: Getting Started', 'Learn the essential principles of time management and productivity. This foundational guide covers the core concepts you need to master for effective personal and professional organization.', '', 'publish', 'page', DATE_SUB(NOW(), INTERVAL 200 DAY), DATE_SUB(NOW(), INTERVAL 200 DAY), DATE_SUB(NOW(), INTERVAL 200 DAY), DATE_SUB(NOW(), INTERVAL 200 DAY), 1, 'closed', 'closed', 'time-management-fundamentals-starting', 0, 0, '', 0, '', '', ''),
('Focus and Concentration Techniques', 'Master the art of focus and concentration with proven techniques and strategies. Learn how to eliminate distractions and maintain deep attention for extended periods.', '', 'publish', 'page', DATE_SUB(NOW(), INTERVAL 300 DAY), DATE_SUB(NOW(), INTERVAL 300 DAY), DATE_SUB(NOW(), INTERVAL 300 DAY), DATE_SUB(NOW(), INTERVAL 300 DAY), 1, 'closed', 'closed', 'focus-concentration-techniques', 0, 0, '', 0, '', '', ''),
('Goal Setting and Achievement Strategies', 'Discover effective goal-setting methodologies and learn how to create actionable plans that lead to consistent achievement. Master the art of turning dreams into reality.', '', 'publish', 'page', DATE_SUB(NOW(), INTERVAL 400 DAY), DATE_SUB(NOW(), INTERVAL 400 DAY), DATE_SUB(NOW(), INTERVAL 400 DAY), DATE_SUB(NOW(), INTERVAL 400 DAY), 1, 'closed', 'closed', 'goal-setting-achievement-strategies', 0, 0, '', 0, '', '', ''),
('Work-Life Balance: Finding Your Equilibrium', 'Learn how to create sustainable work-life balance that supports both your professional success and personal well-being. Discover strategies for managing competing priorities effectively.', '', 'publish', 'page', DATE_SUB(NOW(), INTERVAL 500 DAY), DATE_SUB(NOW(), INTERVAL 500 DAY), DATE_SUB(NOW(), INTERVAL 500 DAY), DATE_SUB(NOW(), INTERVAL 500 DAY), 1, 'closed', 'closed', 'work-life-balance-equilibrium', 0, 0, '', 0, '', '', '');

-- Display summary
SELECT 
    'Productivity & Time Management test data creation complete!' as message,
    COUNT(*) as total_posts,
    SUM(CASE WHEN post_type = 'post' THEN 1 ELSE 0 END) as posts,
    SUM(CASE WHEN post_type = 'page' THEN 1 ELSE 0 END) as pages
FROM wp_posts 
WHERE post_title LIKE '%Pomodoro%' 
   OR post_title LIKE '%Time Blocking%'
   OR post_title LIKE '%Eisenhower%'
   OR post_title LIKE '%Digital Minimalism%'
   OR post_title LIKE '%Two-Minute Rule%'
   OR post_title LIKE '%Deep Work%'
   OR post_title LIKE '%Getting Things Done%'
   OR post_title LIKE '%Morning Routines%'
   OR post_title LIKE '%Power of Saying No%'
   OR post_title LIKE '%Batch Processing%'
   OR post_title LIKE '%Habit Stacking%'
   OR post_title LIKE '%80/20 Rule%'
   OR post_title LIKE '%Energy Management%'
   OR post_title LIKE '%Single-Tasking%'
   OR post_title LIKE '%Power of Deadlines%'
   OR post_title LIKE '%Work-Life Balance%'
   OR post_title LIKE '%Compound Effect%'
   OR post_title LIKE '%Psychology of Procrastination%'
   OR post_title LIKE '%Mind Mapping%'
   OR post_title LIKE '%Science of Motivation%'
   OR post_title LIKE '%Decision Fatigue%'
   OR post_title LIKE '%Art of Delegation%'
   OR post_title LIKE '%Myth of Multitasking%'
   OR post_title LIKE '%Building a Second Brain%'
   OR post_title LIKE '%Power of Systems%'
   OR post_title LIKE '%Stress Management%'
   OR post_title LIKE '%Future of Work%'
   OR post_title LIKE '%Productivity Revolution%'
   OR post_title LIKE '%Mastering the Art of Focus%'
   OR post_title LIKE '%Psychology of Peak Performance%'
   OR post_title LIKE '%Building Sustainable Productivity%'
   OR post_title LIKE '%Fundamentals of Time Management%'
   OR post_title LIKE '%Productivity Resources%'
   OR post_title LIKE '%Time Management Fundamentals%'
   OR post_title LIKE '%Focus and Concentration%'
   OR post_title LIKE '%Goal Setting%'
   OR post_title LIKE '%Work-Life Balance%';
